namespace SpirvReflectSharp
{
	/// <summary>
	/// A SPIR-V shader compiler
	/// </summary>
	public enum Generator : int
	{
		KHRONOS_LLVM_SPIRV_TRANSLATOR = 6,
		KHRONOS_SPIRV_TOOLS_ASSEMBLER = 7,
		KHRONOS_GLSLANG_REFERENCE_FRONT_END = 8,
		GOOGLE_SHADERC_OVER_GLSLANG = 13,
		GOOGLE_SPIREGG = 14,
		GOOGLE_RSPIRV = 15,
		X_LEGEND_MESA_MESAIR_SPIRV_TRANSLATOR = 16,
		KHRONOS_SPIRV_TOOLS_LINKER = 17,
		WINE_VKD3D_SHADER_COMPILER = 18,
		CLAY_CLAY_SHADER_COMPILER = 19
	}
}
